### ISSUE TITLE
Clarity on state of code

### ISSUE THREAD

**Issue by flashton2003** [dpasqualin/sfreemap#15]
I saw your publication of this tool in BMC Bioinformatics in February where you say that SFREEMAP is 'accurate and fast', but then I see on the github page that you warn that the code 

'is not production ready. There are still some improvements and tests that need to be done.'

Is this the code which was used to generate the results for the manuscript? Is it ready to be used or not?

Thanks!

**Comment by dpasqualin** [comment]
Yes, this is the code used to generate the results for the manuscript. It is ready to be used. I've removed the warning message from the README.md. Thank you!
