### ISSUE TITLE
Vignette for sfreemap

### ISSUE THREAD

**Issue by flashton2003** [dpasqualin/sfreemap#16]
It would be great if there were a vignette for sfreemap so that we can see how best to use it.

**Comment by dpasqualin** [comment]
There are vignettes, which can be compiled with "build_vignettes()", from the devtools package. 

But to make your life easier, here you go :)
[sfreemap.pdf](https://github.com/dpasqualin/sfreemap/files/1509865/sfreemap.pdf)

**Comment by flashton2003** [comment]
Thanks!
